### ISSUE TITLE
symmetric breaks

### ISSUE THREAD

**Issue by jotsetung** [raivokolde/pheatmap#12]
dear Raivo!
I just switched over from the heatmap.2 function in gplots to your heatmap function, awesome stuff. I'm just missing one tiny thing: would it be possible to add an argument "symbreaks", that forces the generated breaks to be symmetric?

cheers, jo

**Comment by raivokolde** [comment]
Actually pheatmap does it already when you scale the rows. But I see that it can be useful for other cases as well if the values naturally vary around zero. I think about implementing it.

**Comment by jotsetung** [comment]
My solution so far is (Ecent being a matrix with row-centered expression values, but could be anything):
```r
  minmax <- max(abs(Ecent))
  gplot <- pheatmap(Ecent,
           clustering_distance_rows="euclidean",
           clustering_distance_cols="euclidean",
           annotation_col=annot, treeheight_col=20,
           breaks=seq(-minmax, minmax, length.out=101),
           colors=colorRampPalette(rev(brewer.pal(7, "RdYlBu")[-4]))(100)
           )
```
so, priority shouldn't be too high for you, as it is also simple to do with the present implementation.
cheers, jo
