### ISSUE TITLE
Using custom matrix numbers for displaying inside cells

### ISSUE THREAD

**Issue by skyfallen** [raivokolde/pheatmap#24]
Hi, the title says it, the case, which I came across was that I wanted to make log transform on my data, but show original values inside cells. In ggplot2 this could be done easily with stat_bin2d(geom="text", aes(label=..count..)). Maybe could be good to have in pheatmap. The question of course here, is that what kind of scale do you display afterwards, and I don't know the answer.

**Comment by raivokolde** [comment]
You can pass a matrix to `display_numbers` parameter and then these numbers will be shown.

**Comment by skyfallen** [comment]
Cool, thanks!
