### ISSUE TITLE
extracting members of K-means cluster

### ISSUE THREAD

**Issue by abhisheksinghnl** [raivokolde/pheatmap#32]
Hi,

I have a very silly question, could you please help me in resolving it.

I have made a heat map using pheatmap.

pheatmap(t, kmeans_k=65, cluster_cols=F, mypalette3)

This gives me a nice heatmap, now how can I get genenames present in each cluster and save them to a file.

Kindly help.

Best regards
Abhishek

**Comment by raivokolde** [comment]
pheatmap actually returns the invisibly a list where the element called "kmeans" contains the clustering object used to create this plot.
