### ISSUE TITLE
Feature request: legend_font_size and subtitle.

### ISSUE THREAD

**Issue by endrebak** [raivokolde/pheatmap#60]
First of all, thanks for the great software.

I have a feature request: I want the title font to be a different size than the legend text. Would it be possible to set the font size of the legends independently? 

As you can see, having the legend and title the same size is not pretty:

![pheatmap_H3K4me3_hg38_6_20000](https://user-images.githubusercontent.com/17778898/64152938-fa516800-ce2d-11e9-9b95-9a51e355f250.jpg)

Also, the whole legend does not show. 

(Also it would be nice with the option of a subtitle, which should have its own default font size.)

**Comment by vertesy** [comment]
I actually also miss both the `subtitle` and `caption`. In many cases I need to add explanations, note parameters, etc.
