### ISSUE TITLE
Annotation_col Error - subscript out of bounds

### ISSUE THREAD

**Issue by TimJCooper** [raivokolde/pheatmap#65]
**Test dataset**: https://www.dropbox.com/s/hy56owg4mfjuxol/Test_Data.RData?dl=0
Plotting this dataset runs as expected:
`  pheatmap(t(pred.MDSC$scores), fontsize=8)`
![Pheatmap](https://user-images.githubusercontent.com/32513989/74231648-bc574a80-4ccf-11ea-8966-7e937fdae195.png)
However, if I then attempt to add annotation to it:
```
  anno<-data.frame(pred.MDSC$labels)
  pheatmap(t(pred.MDSC$scores), fontsize=8, annotation_col = anno)
```
It returns the error:
```
Error in annotation_colors[[colnames(annotation)[i]]] : 
  subscript out of bounds
```
Is this a bug, or am I doing something wrong with the annotation data structure?

**Comment by sscall** [comment]
I'm having the same issue now and can't figure out why it won't work. Would you mind posting an update to cover how you resolved the issue? Other sources I can find online all recommend ensuring that row names for the annotation and the matrix are equal to one another, but even after doing that, I'm getting the exact same error message.

**Comment by mcanouil** [comment]
@raivokolde Any chance of an update on this?

Here a reprex:

```r
dta <- iris[, 1:4]
annotation <- iris[, "Species", drop = FALSE]
randoid <- rownames(iris)
pheatmap::pheatmap(
  mat = dta,
  annotation_row = annotation,
  labels_row = randoid
)
pheatmap::pheatmap(
  mat = dta[rownames(dta), ],
  annotation_row = annotation,
  labels_row = randoid
)
```

**Comment by raivokolde** [comment]
The problem here is that the pheatmap expects a matrix with row and column names as an input. Here, it is a data.frame instead. It will be converted to a matrix internally, but for some reason `as.matrix(dta[rownames(dta), ])` has rownames and `as.matrix(dta)` doesn't. Not sure how to adjust the pheatmap code to avoid this problem though.

**Comment by mcanouil** [comment]
Two choices,
- forbid `data.frame` and ensure the provided matrix has row names.
- Use the `as.matrix` S3 method and the "rownames.force" argument: `as.matrix(iris, rownames.force = TRUE)`
